import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'routes.dart';
import 'services/auth_service.dart';
import 'services/leaderboard_service.dart';
import 'theme/app_theme.dart';

// ── Shared service singletons ─────────────────────────────────────────────────
// Firebase is optional — the app runs fully without it using local saves.
// To enable Firebase:
//   1. Create a Firebase project at https://console.firebase.google.com
//   2. Run `flutterfire configure` in this directory
//   3. Uncomment the Firebase block below and import firebase_options.dart

late final AuthService        appAuth;
LeaderboardService?           appLeaderboard; // null when Firebase not configured

// ─────────────────────────────────────────────────────────────────────────────

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ── Orientation + display ─────────────────────────────────────────────────
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);
  await SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);

  // ── Auth + Cloud Save (Firebase — uncomment when configured) ──────────────
  //
  // import 'package:firebase_core/firebase_core.dart';
  // import 'firebase_options.dart';        // generated by `flutterfire configure`
  // import 'services/cloud_save_service.dart';
  //
  // try {
  //   await Firebase.initializeApp(
  //     options: DefaultFirebaseOptions.currentPlatform,
  //   );
  //   appAuth = AuthService();
  //   await appAuth.signInAnonymously();
  //   SaveManager.cloudSave = CloudSaveService(auth: appAuth);
  //   appLeaderboard = LeaderboardService(auth: appAuth);
  // } catch (e) {
  //   debugPrint('Firebase init failed — local-only mode. $e');
  //   appAuth = AuthService();
  //   appLeaderboard = null;
  // }

  // ── Offline-only initialisation (active until Firebase is configured) ─────
  appAuth = AuthService();
  // SaveManager uses local shared_preferences only (SaveManager.cloudSave == null).

  runApp(const EscapeVerseApp());
}

// ─────────────────────────────────────────────────────────────────────────────

class EscapeVerseApp extends StatelessWidget {
  const EscapeVerseApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'EscapeVerse',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.dark,
      initialRoute: AppRoutes.home,
      onGenerateRoute: onGenerateRoute,
    );
  }
}
